### ISSUE TITLE
Extension does not contribute the required settings to configure Jira

### ISSUE THREAD

**Issue by crhistianramirez** [JesseChrestler/jira-search-vscode-extension#1]
I have:

- VSCode Version 1.15.0 (1.15.0) (most recent)
- 2015 Macbook Pro
- OSX El Capitan Version 10.11.6

but am not seeing the necessary settings to configure jira. 

I've tried restarting VSCode and doing a clean install

**Comment by JesseChrestler** [comment]
I will take a look and see if I can reproduce this issue.

**Comment by JesseChrestler** [comment]
I was able to use the JIRA Search with no issues. You can access the settings in File -> Preferences -> Settings

you will see it open up two files left being default settings, and the right being user settings. On the right side paste the configuration settings for jiraSearch.
{
 "jiraSearch.url": "https://subdomain.atlassian.net",
 "jiraSearch.username": "userername",
 "jiraSearch.password": "password"
}

let me know if you still have  questions I will do what i can to help.
